/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesgui;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SalesApp extends javax.swing.JFrame {

    /**
     * Creates new form SalesApp
     */
    public SalesApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        contactPreference = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        districtGroup = new javax.swing.ButtonGroup();
        submitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salesIdInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        booksSoldInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        suppliesSoldInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        paperSoldInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emButton = new javax.swing.JRadioButton();
        pButton = new javax.swing.JRadioButton();
        vButton = new javax.swing.JRadioButton();
        nButton = new javax.swing.JRadioButton();
        sButton = new javax.swing.JRadioButton();
        eButton = new javax.swing.JRadioButton();
        wButton = new javax.swing.JRadioButton();
        statusLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesOutput = new javax.swing.JTextArea();
        evalButton = new javax.swing.JButton();

        jTextField9.setText("jTextField9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submitButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Last Name:");

        firstNameInput.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        firstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameInputActionPerformed(evt);
            }
        });

        lastNameInput.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Sales Rep ID:");

        salesIdInput.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        salesIdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesIdInputActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Books Sold:");

        booksSoldInput.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Office Supplies Sold:");

        suppliesSoldInput.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Paper Sold:");

        paperSoldInput.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        paperSoldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperSoldInputActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Preferred contact method:");

        quitButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("District: ");

        contactPreference.add(emButton);
        emButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        emButton.setText("Email");
        emButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emButtonActionPerformed(evt);
            }
        });

        contactPreference.add(pButton);
        pButton.setText("Phone");

        contactPreference.add(vButton);
        vButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vButton.setText("Visit");

        districtGroup.add(nButton);
        nButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nButton.setText("North");

        districtGroup.add(sButton);
        sButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sButton.setText("South");

        districtGroup.add(eButton);
        eButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        eButton.setText("East");

        districtGroup.add(wButton);
        wButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        wButton.setText("West");

        statusLabel.setForeground(new java.awt.Color(0, 204, 204));

        salesOutput.setEditable(false);
        salesOutput.setColumns(20);
        salesOutput.setRows(5);
        jScrollPane1.setViewportView(salesOutput);

        evalButton.setText("Evaluate");
        evalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(suppliesSoldInput))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(booksSoldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(salesIdInput))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lastNameInput))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(paperSoldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(submitButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(132, 132, 132)
                                        .addComponent(statusLabel))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(evalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salesIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(booksSoldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suppliesSoldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(paperSoldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(emButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton)
                    .addComponent(vButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nButton)
                    .addComponent(sButton)
                    .addComponent(eButton)
                    .addComponent(wButton))
                .addGap(18, 18, 18)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(quitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evalButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesIdInputActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void paperSoldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperSoldInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paperSoldInputActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       
        boolean allDataRecieved = true;
        SalesRep s = new SalesRep();
        
        String name = firstNameInput.getText();
       if(name.trim().length() == 0)
       {
           JOptionPane.showMessageDialog(this, " You must enter a valid First name ");
           allDataRecieved = false;
       }else
       {
       firstNameInput.setText(name.trim());
       s.setFirstName(name.trim());
       
       }
       
       String lastName = lastNameInput.getText();
       if(lastName.trim().length() == 0)
       {
           JOptionPane.showMessageDialog(this, " You must provide Last name ");
           allDataRecieved = false;
           
       }else
       {
       lastNameInput.setText(lastName.trim());
       s.setLastName(lastName.trim());
       
       }
       
       String ID = salesIdInput.getText();
       try
       {
           int repID = Integer.parseInt(ID);
           if(repID < 1)
           {
           
            JOptionPane.showMessageDialog(this, " ID cannot be less than 1 ");
           allDataRecieved = false;
           
           }else
           {
               s.setRepID(repID);
           }
       }catch (NumberFormatException e)
       {
           JOptionPane.showMessageDialog(this, " ID must be an integer ");
           allDataRecieved = false;
       } 
       
       String sbook = booksSoldInput.getText(); 
       try{
         
           double book = Double.parseDouble(sbook);
           if (book < 1)
           {
                 JOptionPane.showMessageDialog(this, " Books Sold cannot be less than 1 ");
           allDataRecieved = false;
           
           }else
           {
           s.setBooksSold(book);
           }
       }catch (NumberFormatException e)
       {
       
           JOptionPane.showMessageDialog(this, " Books Sold must be an integer ");
           allDataRecieved = false;
       }
       
       String sSold = suppliesSoldInput.getText();
       try{
           double supplies =  Double.parseDouble(sSold);
           if(supplies < 1)
           {
               JOptionPane.showMessageDialog(this, " Office Supplies Sold cannot be less than 1 ");
           allDataRecieved = false;
           
           }else
           {
           s.setSuppliesSold(supplies);
           
           }
       
       }catch(NumberFormatException e)
       {
       
           JOptionPane.showMessageDialog(this, " Office Supplies Sold must be an integer ");
           allDataRecieved = false;
       }
       String pSold = paperSoldInput.getText();
       try{
           double paper = Double.parseDouble(pSold);
           if(paper < 1)
           {
               JOptionPane.showMessageDialog(this, " Paper Sold cannot be less than 1 ");
           allDataRecieved = false;
           
           }else
           {
           s.setPaperSold(paper);
           }
       
       }catch(NumberFormatException e)
       {
       
             JOptionPane.showMessageDialog(this, " Paper Sold must be an integer ");
           allDataRecieved = false;
       }
       
       
       if(emButton.isSelected())
       {
       s.setContact("Email ");
       }else if(pButton.isSelected())
       {
           s.setContact("Phone ");
            
    
       
       }else if(vButton.isSelected())
       {
           
       s.setContact("visit ");
       }else
       {
       JOptionPane.showMessageDialog(this, " Please select a contact method ");
       allDataRecieved = false;
       }
               
        if (nButton.isSelected())
        {
        s.setDistrict("North ");
        
        }else if(sButton.isSelected())
        {
        s.setDistrict("South ");
        }else if(eButton.isSelected())
        {
        s.setDistrict("East ");
        }else if(wButton.isSelected())
        {
        s.setDistrict("West ");
        }else
        {
        JOptionPane.showMessageDialog(this, " Please select a valid District ");
        allDataRecieved = false;
        }
               
       if(allDataRecieved)
       
       {
      
        
            try {
                SalesFileStorage sfs = new SalesFileStorage();
            
                sfs.writeSales(s);
                statusLabel.setText("Succesfully Submitted!");
                firstNameInput.setText("");
                lastNameInput.setText("");
                salesIdInput.setText("");
                booksSoldInput.setText("");
                suppliesSoldInput.setText("");
                paperSoldInput.setText("");
                nButton.setSelected(false);
                sButton.setSelected(false);
                eButton.setSelected(false);
                wButton.setSelected(false);
                emButton.setSelected(false);
                pButton.setSelected(false);
                vButton.setSelected(false);
                
            } catch (IOException ex) {
                
                  JOptionPane.showMessageDialog(this, " Error cannot find File ");
                Logger.getLogger(SalesApp.class.getName()).log(Level.SEVERE, null, ex);
            }
        
       }
       
    }//GEN-LAST:event_submitButtonActionPerformed

    private void firstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameInputActionPerformed

    private void emButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emButtonActionPerformed

    private void evalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evalButtonActionPerformed
       SalesReader sr = new SalesReader();
        try {
            List<SalesRep> sales = sr.readSales("Stars.txt");
            for (SalesRep s : sales)
            if(s.getBooksSold() + s.getPaperSold() + s.getSuppliesSold() >= 8000)
            {
              StarsFile sFile = new StarsFile();
              sFile.writeStar(s);
               
               firstNameInput.setText("");
                lastNameInput.setText("");
                salesIdInput.setText("");
                booksSoldInput.setText("");
                suppliesSoldInput.setText("");
                paperSoldInput.setText("");
                nButton.setSelected(false);
                sButton.setSelected(false);
                eButton.setSelected(false);
                wButton.setSelected(false);
                emButton.setSelected(false);
                pButton.setSelected(false);
                vButton.setSelected(false);
                
                
              salesOutput.append(s.toString());
             salesOutput.append("\n");
            }
                
            
                
             
            
        } catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Unable to open file");
            Logger.getLogger(SalesApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_evalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SalesApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField booksSoldInput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup contactPreference;
    private javax.swing.ButtonGroup districtGroup;
    private javax.swing.JRadioButton eButton;
    private javax.swing.JRadioButton emButton;
    private javax.swing.JButton evalButton;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JRadioButton nButton;
    private javax.swing.JRadioButton pButton;
    private javax.swing.JTextField paperSoldInput;
    private javax.swing.JButton quitButton;
    private javax.swing.JRadioButton sButton;
    private javax.swing.JTextField salesIdInput;
    private javax.swing.JTextArea salesOutput;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField suppliesSoldInput;
    private javax.swing.JRadioButton vButton;
    private javax.swing.JRadioButton wButton;
    // End of variables declaration//GEN-END:variables
}
